
parser:
  babel-eslint

plugins:
  - css-modules

extends:
  - airbnb
  - plugin:css-modules/recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings

env:
  browser: true
