
parser:
  babel-eslint

plugins:
  - css-modules

extends:
  - airbnb
  - plugin:css-modules/recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings

env:
  browser: true

rules:
  padded-blocks: off

  # Loose restriction on indentation and member ordering in React/JSX
  react/sort-comp: off
  react/jsx-first-prop-new-line: off
  react/jsx-closing-bracket-location: off

